#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Fortizo.Resource", IsApplication=true)]

namespace Fortizo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Fortizo.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Fortizo.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Fortizo.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backArrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DropDownBackGround = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int frontImg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Layout_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mainmenurec = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MobileNetworkSelecter = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int QR_Scanner = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int scan = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SettingRectangle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int SettingsLine = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int About = 2131099691;
			
			// aapt resource value: 0x7f060002
			public const int AboutPageBackArrow = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int AboutPageBackText = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int AvailableCountriesContainer = 2131099672;
			
			// aapt resource value: 0x7f06002f
			public const int AvailableMobileNetworks = 2131099695;
			
			// aapt resource value: 0x7f06000d
			public const int BalanceCheck = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int Botswana = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int CountryBackArrow = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int CountryPageBackText = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int CountrySelecter = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int CustomerCare = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int DataBundles = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int Dubai = 2131099674;
			
			// aapt resource value: 0x7f060021
			public const int ElectricityPageBackArrow = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int ElectricityPageBackText = 2131099682;
			
			// aapt resource value: 0x7f060013
			public const int ElectricityScan = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int Ghana = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int Malawi = 2131099676;
			
			// aapt resource value: 0x7f060024
			public const int MeterNumberInput = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int MeterNumberPlaceHolder = 2131099683;
			
			// aapt resource value: 0x7f060028
			public const int MobileSelectLink = 2131099688;
			
			// aapt resource value: 0x7f06001d
			public const int Namibia = 2131099677;
			
			// aapt resource value: 0x7f060030
			public const int Network1 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int Network2 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int Network3 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int Network4 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int Network5 = 2131099700;
			
			// aapt resource value: 0x7f06002c
			public const int NetworkBackBtn = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int NetworkPageHeading = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int NetworkSelecter = 2131099694;
			
			// aapt resource value: 0x7f060029
			public const int PrepaidElectricityLink = 2131099689;
			
			// aapt resource value: 0x7f06001e
			public const int SA = 2131099678;
			
			// aapt resource value: 0x7f060025
			public const int SaveElectricitySettingsBtn = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int SettingsBackBtn = 2131099686;
			
			// aapt resource value: 0x7f06000b
			public const int SettingsLink = 2131099659;
			
			// aapt resource value: 0x7f060027
			public const int SettingsPageHeading = 2131099687;
			
			// aapt resource value: 0x7f060016
			public const int StoredNetwork = 2131099670;
			
			// aapt resource value: 0x7f06001f
			public const int Zambia = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int Zim = 2131099680;
			
			// aapt resource value: 0x7f060012
			public const int button = 2131099666;
			
			// aapt resource value: 0x7f060035
			public const int contentFrame = 2131099701;
			
			// aapt resource value: 0x7f060010
			public const int imageView1 = 2131099664;
			
			// aapt resource value: 0x7f06002a
			public const int imageView2 = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int relativeLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int relativeLayout2 = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int scroll = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int textView2 = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView4 = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int textView5 = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int textView6 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Country = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ElectricitySettings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int menuPage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectMobileNetwork = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyCustomTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
